### ISSUE TITLE
[gadget] phploc

### ISSUE THREAD

**Issue by DavidBadura** [simpspector/analyser#47]
https://github.com/sebastianbergmann/phploc

**Comment by tolry** [comment]
This would a gadget only gathering statistical data right? Or would this influence the score in any way? LOC are obviously not a good measure for code quality in any way, we have the mess detector using cyclomatic complexity for this, which is much more valuable.

Especially when analyzing only parts of the code base most of the time (only files changed by merge requests), this metric would not be of any use, or am I missing a use case?

**Comment by DavidBadura** [comment]
The goal of the analyser should be to aggregate and normalize issues and metrics on one place. And not only für simpspector, rather for the general public. How to calculate the score is a own thopic. It can be caclulate with `cyclomatic complexity` or with `lines of code`. That should decide simpspector or other projects.

btw. objective score calculating is very complex. slowly i am against to provide a general score. I'd rather see the changes in the metrics, then I can judge for themselves if it was better or not.

**Comment by tolry** [comment]
Overall scores are always ... ehrm ... problematic (unless its that new smartphone that got 97 out of 100 points, must be bonkers :wink:). I see your point and agree with you on it not being the analyser's place to calculate the score.

But I am still struggling to see the value of this gadget, since it would almost exclusively generate metrics and those are right now e.g. not build to handle one metric per file, are they, we would probably have to rethink the architecture there. Average LOC values as phploc generates them are hard interpret and have almost no analytic value.

Only relevant use cases I see right now: 

* raise an issue for every class/file with >`configurable line number here` lines
* use the information for cyclomatic complexity (we already have this in phpmd)

**Comment by DavidBadura** [comment]
i think we can close this issue because pdepend also has metrics like `loc` etc.
http://pdepend.org/documentation/software-metrics/index.html

will be added with #52
